#!/bin/bash
#
#  00-bootup-logo
#
#  Display a bootup logo image if available.
#

logo_file="/usr/share/pipaos-tools/logos/default.png"
if [ -f "$logo_file" ]; then
    layer=1
    /usr/share/raspidmx/samples/pngview -n -l $layer "$logo_file" &
fi
