#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          pipaos-init-network
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Prepare network on boot
# Description:       Allows to setup network details on the /boot partition
### END INIT INFO

PATH="/sbin:/bin"

. /lib/lsb/init-functions

pipaos_network=/boot/interfaces.txt
system_network=/etc/network/interfaces

case "$1" in
    start)
        log_warning_msg "Populating pipaos network settings $pipaos_network"
        cp -fv $pipaos_network $system_network
        log_action_end_msg $?
        ;;
    
    stop)
        ;;

    reload)
        log_warning_msg "Updating pipaos network settings $pipaos_network"
        cp -fv $pipaos_network $system_network
        ;;

    force-reload|restart)
        ;;

esac

exit 0
