#!/bin/bash
#
# debian postinst script
#

initd_script="/etc/init.d/pipaos-init-network"
systemd_script="/usr/lib/systemd/pipaos-init-network.service"

case "$1" in

    remove|upgrade)
        if [ -f "$initd_script" ]; then
            rm "$initd_script"
        fi

        if [ -f "$systemd_script" ]; then
            systemctl disable pipaos-init-network
            rm "$systemd_script"
        fi
        ;;
esac

#DEBHELPER#

exit 0
