#!/usr/bin/env python
#
#  Send a network broadcast to tell our IP address
#  Listen with: sudo tcpdump -n udp port 5000
#

sonar_port = 5000

import sys, time
from socket import *

s = socket(AF_INET, SOCK_DGRAM)
s.bind(('', 0))
s.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)

while 1:
    try:
        data = 'pipaos-sonar at {}'.format(repr(time.time()))
        s.sendto(data, ('<broadcast>', sonar_port))
        time.sleep(15)
    except:
        time.sleep(5)
